name: BotCast Auto Task

on:
  schedule:
    # Todos los d√≠as a las 6:00 AM (hora UTC)
    - cron: "0 6 * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt
        
      - name: Listar archivos
        run: ls -R
        
      - name: Ejecutar el bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python Bot.py
